// prisma/assessment-objectives-new.ts
// Objetivos de valoración para TDA, Aprendizaje Lento (APZ_LENTO) y TANV
// Fuente TDA: miscelaneos/Pruebas diagnósticas/TDAH/Dx TDAH.docx (6 áreas × 6 grados)
// Fuente APZ_LENTO: miscelaneos/Pruebas diagnósticas/Aprendizaje lento/Dx Aprendizaje lento.docx (6 áreas × 6 grados)
// Fuente TANV: Cuaderno N°4 Anexo 5 + estándares internacionales (5 áreas × 6 grados)
// Estructura: code = "DIFFICULTY.AREACODE.GRADE.ITEMORDER"
// levelSort: 1-6 para grados, 99 para General

export const ASSESSMENT_OBJECTIVES_NEW = [

  // ============================================================
  // TDA — Trastorno por Déficit de Atención
  // ============================================================

  // ── ÁREA A: INATENCIÓN SOSTENIDA Y FLUCTUANTE ──
  { code: "TDA.A.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Mantiene el foco en tareas visuales simples (completar series, colorear) sin recordatorios durante 2–3 minutos" },
  { code: "TDA.A.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Puede escuchar un cuento corto y responder preguntas básicas sobre él sin haberse desconectado" },
  { code: "TDA.A.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Mantiene el criterio de búsqueda o conteo en una imagen compleja sin desviarse a otros elementos" },
  { code: "TDA.A.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Copia oraciones cortas sin perder el hilo ni desviar la vista repetidamente del modelo" },
  { code: "TDA.A.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Detecta letras o símbolos en un texto sin que su rendimiento disminuya significativamente al final del tiempo asignado" },
  { code: "TDA.A.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Completa operaciones aritméticas repetitivas con consistencia, sin errores por descuido frecuentes" },
  { code: "TDA.A.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Compara listas con errores intencionales y los detecta de forma exhaustiva durante el tiempo asignado" },
  { code: "TDA.A.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Lee un párrafo informativo y extrae detalles específicos sin relectura excesiva ni señales de desconexión" },
  { code: "TDA.A.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Completa tareas de selección múltiple o llenar espacios manteniendo el esfuerzo mental durante 10–12 minutos" },
  { code: "TDA.A.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Toma apuntes de una explicación oral corta identificando ideas clave sin perder información importante" },
  { code: "TDA.A.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Revisa textos detectando errores gramaticales u ortográficos de forma sistemática sin que su capacidad disminuya con el tiempo" },
  { code: "TDA.A.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "A", areaLabel: "INATENCIÓN SOSTENIDA Y FLUCTUANTE", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Resuelve problemas matemáticos de varios pasos manteniendo el hilo de resolución hasta el final" },

  // ── ÁREA B: DISTRACTIBILIDAD (ATENCIÓN SELECTIVA) ──
  { code: "TDA.B.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "No se desvía frecuentemente hacia distractores visuales periféricos durante tareas de dibujo o coloreado" },
  { code: "TDA.B.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Puede realizar emparejamiento de figuras con ruido suave de fondo sin interrupciones frecuentes" },
  { code: "TDA.B.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Busca letras o números en una cuadrícula con \"ruido visual\" manteniendo el foco en el criterio correcto" },
  { code: "TDA.B.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Sigue instrucciones de 2–3 pasos sin perder el hilo ante comentarios irrelevantes del evaluador" },
  { code: "TDA.B.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Lee un párrafo con imágenes no relacionadas intercaladas sin que afecte su comprensión" },
  { code: "TDA.B.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Realiza tareas matemáticas con distractores auditivos moderados sin que su velocidad o precisión disminuyan significativamente" },
  { code: "TDA.B.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "En tareas de edición, distingue errores reales de \"señuelos\" visuales sin ser desviado por palabras inusuales pero correctas" },
  { code: "TDA.B.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Retoma la tarea académica con rapidez tras una interrupción personal o interna" },
  { code: "TDA.B.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Busca datos en tablas complejas filtrando información numérica irrelevante sin confundir datos similares" },
  { code: "TDA.B.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Mantiene rendimiento en tareas individuales ante distractores sociales (otros estudiantes conversando cerca)" },
  { code: "TDA.B.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Lee un texto de estudio con múltiples elementos gráficos laterales y responde preguntas sobre el contenido principal" },
  { code: "TDA.B.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "B", areaLabel: "DISTRACTIBILIDAD (ATENCIÓN SELECTIVA)", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Resuelve problemas complejos manteniendo el foco ante múltiples distractores auditivos y visuales simultáneos" },

  // ── ÁREA C: CONTROL DE IMPULSOS ──
  { code: "TDA.C.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Puede inhibir una acción motora cuando la regla lo indica (ej. \"Simón Dice\" con palabra clave)" },
  { code: "TDA.C.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Espera su turno en juegos simples sin tocar piezas ajenas ni actuar antes de que le corresponda" },
  { code: "TDA.C.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Puede inhibir respuestas automáticas ante preguntas \"trampa\" (piensa antes de responder)" },
  { code: "TDA.C.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Inhibe la respuesta motora ante el estímulo \"No hacer\" en tareas de tipo Go/No-Go" },
  { code: "TDA.C.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Respeta el turno de palabra en conversaciones estructuradas sin interrumpir frecuentemente" },
  { code: "TDA.C.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "En tareas de clasificación con penalización por impulsividad, considera las consecuencias antes de actuar" },
  { code: "TDA.C.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Lee todas las opciones de respuesta antes de elegir, evitando seleccionar la primera opción obvia sin reflexionar" },
  { code: "TDA.C.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "En juegos de estrategia sencilla, se toma tiempo para considerar sus opciones antes de mover" },
  { code: "TDA.C.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Bajo presión de tiempo, no escribe la primera idea impulsivamente sino que elabora una respuesta más reflexiva" },
  { code: "TDA.C.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "En debates o discusiones, respeta las pausas y no responde antes de escuchar la idea completa del interlocutor" },
  { code: "TDA.C.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Ante problemas de lógica con respuesta obvia incorrecta, inhibe la primera idea y explora alternativas" },
  { code: "TDA.C.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "C", areaLabel: "CONTROL DE IMPULSOS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Ante situaciones de conflicto social hipotéticas, genera respuestas reflexivas en lugar de reacciones impulsivas" },

  // ── ÁREA D: HIPERACTIVIDAD MOTORA Y VERBAL ──
  { code: "TDA.D.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Durante tareas individuales sentado (5 min), no presenta movimientos excesivos ni abandona el asiento sin permiso" },
  { code: "TDA.D.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "En actividades de grupo, su nivel de energía y actividad verbal es acorde al contexto" },
  { code: "TDA.D.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "En dictados con movimiento estructurado, realiza los movimientos de forma controlada y regresa al asiento sin excederse" },
  { code: "TDA.D.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "En conversación sobre temas de interés, no habla en exceso ni salta de tema sin terminar las ideas" },
  { code: "TDA.D.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "En tareas repetitivas largas (7–10 min), no presenta golpeteo constante, cambios de postura frecuentes ni ruidos" },
  { code: "TDA.D.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "En actividades de lectura compartida, puede participar de forma relativamente tranquila" },
  { code: "TDA.D.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Durante escritura libre, no presenta movimiento excesivo del cuerpo ni manipulación constante de materiales" },
  { code: "TDA.D.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "En presentaciones orales cortas, habla de forma organizada sin divagar ni moverse excesivamente" },
  { code: "TDA.D.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Durante estudio individual en grupo, no genera ruidos ni movimientos que distraigan a sus compañeros" },
  { code: "TDA.D.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "En diálogos grupales estructurados, regula su habla sin dominar ni interrumpir constantemente" },
  { code: "TDA.D.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "En tareas de larga duración (20–25 min), puede mantenerse sentado con movimientos discretos y controlados" },
  { code: "TDA.D.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "D", areaLabel: "HIPERACTIVIDAD MOTORA Y VERBAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "En trabajo colaborativo, gestiona su nivel de actividad y verbalización de forma apropiada para el trabajo en equipo" },

  // ── ÁREA E: ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS ──
  { code: "TDA.E.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Reúne los materiales solicitados para una tarea de forma autónoma y sin distraerse" },
  { code: "TDA.E.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Sigue una secuencia de 2–3 pasos conocidos en el orden correcto completando cada paso antes del siguiente" },
  { code: "TDA.E.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Guarda sus útiles de forma organizada y recuerda hacerlo sin que queden materiales fuera" },
  { code: "TDA.E.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Antes de iniciar un dibujo complejo, puede describir brevemente el orden en que dibujará los elementos" },
  { code: "TDA.E.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Inicia las tareas asignadas sin procrastinar y hace la transición entre tareas con fluidez" },
  { code: "TDA.E.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Mantiene los materiales organizados durante actividades largas de manualidades o construcción" },
  { code: "TDA.E.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Produce un esquema o lista de ideas antes de escribir una historia corta y lo sigue durante la escritura" },
  { code: "TDA.E.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Distribuye el tiempo disponible entre dos tareas académicas cortas de forma razonablemente eficiente" },
  { code: "TDA.E.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Al planificar una mini-investigación, puede desglosar los pasos y proponer cómo organizar la información" },
  { code: "TDA.E.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Su cuaderno o carpeta de una asignatura muestra organización mínima (fechas, secciones, sin perder hojas)" },
  { code: "TDA.E.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Al planificar tareas semanales, establece prioridades y estima tiempos de forma razonable" },
  { code: "TDA.E.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "E", areaLabel: "ORGANIZACIÓN, PLANIFICACIÓN Y FINALIZACIÓN DE TAREAS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "En un trabajo escrito de varias partes, completa todas las etapas sin omitir la revisión ni dejar partes inconclusas" },

  // ── ÁREA F: MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES ──
  { code: "TDA.F.1.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Repite correctamente secuencias de 2–3 palabras no relacionadas en el mismo orden" },
  { code: "TDA.F.1.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Sigue instrucciones verbales de dos pasos realizando ambos en el orden correcto sin recordatorios" },
  { code: "TDA.F.2.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Repite secuencias directas de 3–4 números sin omisiones ni sustituciones frecuentes" },
  { code: "TDA.F.2.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Sigue instrucciones de tres pasos simples sin olvidar el último paso ni invertir el orden" },
  { code: "TDA.F.3.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Repite secuencias de 3–4 palabras no relacionadas con errores de omisión, sustitución u orden mínimos" },
  { code: "TDA.F.3.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Sigue instrucciones de 3 pasos con conceptos espaciales sin confundir posiciones ni olvidar acciones" },
  { code: "TDA.F.4.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Puede repetir secuencias de 2–3 números en orden inverso (memoria de trabajo operativa)" },
  { code: "TDA.F.4.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Sigue instrucciones de 4 pasos o con condición simple completando todos los pasos sin ayuda verbal frecuente" },
  { code: "TDA.F.5.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Repite frases de 8–10 palabras conservando los detalles clave sin omitir elementos importantes" },
  { code: "TDA.F.5.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Sigue instrucciones de 5 pasos o con doble condición sin confundir el orden ni omitir condiciones" },
  { code: "TDA.F.6.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Retiene los datos de un problema matemático verbal y explica los pasos de resolución en el orden correcto" },
  { code: "TDA.F.6.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "F", areaLabel: "MEMORIA DE TRABAJO Y SEGUIMIENTO DE INSTRUCCIONES", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Sigue instrucciones complejas de 6 pasos o con excepciones sin requerir recordatorios frecuentes" },

  // ── ÁREA G: INDICADORES CONDUCTUALES Y EMOCIONALES (general) ──
  { code: "TDA.G.G.1", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "G", areaLabel: "INDICADORES CONDUCTUALES Y EMOCIONALES", level: "G", levelLabel: "General", levelType: "checkbox", levelSort: 99, itemOrder: 1, description: "Muestra tolerancia a la frustración adecuada; no abandona tareas ni reacciona con enojo intenso ante errores" },
  { code: "TDA.G.G.2", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "G", areaLabel: "INDICADORES CONDUCTUALES Y EMOCIONALES", level: "G", levelLabel: "General", levelType: "checkbox", levelSort: 99, itemOrder: 2, description: "Mantiene estabilidad emocional durante las sesiones sin cambios de humor abruptos" },
  { code: "TDA.G.G.3", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "G", areaLabel: "INDICADORES CONDUCTUALES Y EMOCIONALES", level: "G", levelLabel: "General", levelType: "checkbox", levelSort: 99, itemOrder: 3, description: "No muestra irritabilidad ni enojo frecuente durante las actividades de evaluación o trabajo" },
  { code: "TDA.G.G.4", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "G", areaLabel: "INDICADORES CONDUCTUALES Y EMOCIONALES", level: "G", levelLabel: "General", levelType: "checkbox", levelSort: 99, itemOrder: 4, description: "Demuestra autoestima académica y social funcional, sin verbalizaciones de incapacidad constantes" },
  { code: "TDA.G.G.5", difficulty: "TDA", difficultyLabel: "TDA", areaCode: "G", areaLabel: "INDICADORES CONDUCTUALES Y EMOCIONALES", level: "G", levelLabel: "General", levelType: "checkbox", levelSort: 99, itemOrder: 5, description: "Se relaciona con pares y adultos de forma apropiada sin conductas de imposición ni aislamiento" },


  // ============================================================
  // APZ_LENTO — Aprendizaje Lento
  // ============================================================

  // ── ÁREA A: VELOCIDAD DE PROCESAMIENTO ──
  { code: "APZ_LENTO.A.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Clasifica imágenes por categoría simple (animales, colores) en un tiempo comparable a sus pares del grupo" },
  { code: "APZ_LENTO.A.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Completa laberintos simples o une puntos en el tiempo esperado para su edad y grado" },
  { code: "APZ_LENTO.A.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Realiza tareas de emparejamiento visual en tiempo similar al promedio del grupo" },
  { code: "APZ_LENTO.A.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Copia 3–4 números o letras en un tiempo razonablemente comparable al resto del grupo" },
  { code: "APZ_LENTO.A.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Completa 8–10 operaciones aritméticas básicas en el tiempo esperado para su grado" },
  { code: "APZ_LENTO.A.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Escanea visualmente un texto o cuadrícula con velocidad funcional (no excesivamente lenta respecto al grupo)" },
  { code: "APZ_LENTO.A.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Realiza tareas de clasificación o búsqueda de datos con velocidad funcional sin quedar muy rezagado" },
  { code: "APZ_LENTO.A.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Completa actividades de escritura o copia en tiempo razonablemente comparable al grupo con apoyo" },
  { code: "APZ_LENTO.A.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Con tiempo ampliado razonable, puede completar exámenes o tareas académicas" },
  { code: "APZ_LENTO.A.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Su velocidad de procesamiento, aunque más lenta, le permite participar activamente en clase con adaptaciones" },
  { code: "APZ_LENTO.A.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Realiza tareas académicas complejas con velocidad funcional dentro de tiempos ampliados razonables" },
  { code: "APZ_LENTO.A.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "A", areaLabel: "VELOCIDAD DE PROCESAMIENTO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "La lentitud de procesamiento no le impide acceder al currículo con adaptaciones metodológicas" },

  // ── ÁREA B: MEMORIA (CORTO PLAZO Y DE TRABAJO) ──
  { code: "APZ_LENTO.B.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Repite secuencias de 3–4 palabras no relacionadas con errores mínimos" },
  { code: "APZ_LENTO.B.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Recuerda instrucciones de 2 pasos y los realiza en orden sin olvidar el segundo" },
  { code: "APZ_LENTO.B.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Repite secuencias de 3–4 números en orden directo sin omisiones frecuentes" },
  { code: "APZ_LENTO.B.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Recuerda y aplica instrucciones de 3 pasos simples con pocos recordatorios" },
  { code: "APZ_LENTO.B.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Recuerda 3–4 imágenes mostradas brevemente (10 seg.) con precisión razonable" },
  { code: "APZ_LENTO.B.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Sigue instrucciones de 3 pasos con conceptos relacionales (encima, detrás, junto a) sin perder el hilo" },
  { code: "APZ_LENTO.B.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Puede invertir secuencias cortas de 2 números (memoria de trabajo operativa básica)" },
  { code: "APZ_LENTO.B.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Retiene los datos de un problema matemático verbal para resolverlo con apoyo concreto" },
  { code: "APZ_LENTO.B.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Recuerda detalles de un párrafo informativo suficientes para responder preguntas literales" },
  { code: "APZ_LENTO.B.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Sigue instrucciones de 4–5 pasos con apoyo visual o verbal mínimo" },
  { code: "APZ_LENTO.B.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Retiene y puede explicar la secuencia de un procedimiento de varios pasos con apoyos visuales" },
  { code: "APZ_LENTO.B.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "B", areaLabel: "MEMORIA (CORTO PLAZO Y DE TRABAJO)", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "La limitación de memoria no le impide participar en actividades académicas cuando se proveen apoyos visuales" },

  // ── ÁREA C: ATENCIÓN Y CONCENTRACIÓN ──
  { code: "APZ_LENTO.C.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Mantiene la atención en tareas cortas (2–3 min) sin desviarse frecuentemente" },
  { code: "APZ_LENTO.C.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "No muestra resistencia marcada a iniciar actividades o a permanecer en ellas" },
  { code: "APZ_LENTO.C.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Puede trabajar con un ruido suave de fondo sin interrumpir la tarea con frecuencia" },
  { code: "APZ_LENTO.C.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Espera su turno y sigue la secuencia de actividades grupales sin impaciencia excesiva" },
  { code: "APZ_LENTO.C.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Mantiene la atención durante actividades de 7–10 minutos con apoyo o recordatorios ocasionales" },
  { code: "APZ_LENTO.C.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "En tareas medianamente motivantes, no abandona ni se distrae con una frecuencia que impida el avance" },
  { code: "APZ_LENTO.C.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Puede realizar tareas de atención selectiva (buscar errores, identificar criterios) con rendimiento funcional" },
  { code: "APZ_LENTO.C.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Responde preguntas esperando a que estas concluyan, sin interrupciones frecuentes" },
  { code: "APZ_LENTO.C.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Mantiene concentración en actividades de estudio o lectura durante 10–15 minutos con apoyos" },
  { code: "APZ_LENTO.C.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Su nivel de atención le permite participar en las rutinas del aula con adaptaciones metodológicas" },
  { code: "APZ_LENTO.C.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Puede organizarse y mantener el foco en actividades de larga duración con apoyos estructurales" },
  { code: "APZ_LENTO.C.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "C", areaLabel: "ATENCIÓN Y CONCENTRACIÓN", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Su nivel de atención no le impide acceder al currículo con adaptaciones metodológicas planificadas" },

  // ── ÁREA D: COMPRENSIÓN Y RAZONAMIENTO ──
  { code: "APZ_LENTO.D.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Comprende instrucciones de 1–2 pasos presentadas de forma clara y sencilla" },
  { code: "APZ_LENTO.D.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Puede responder preguntas literales sobre un cuento escuchado brevemente" },
  { code: "APZ_LENTO.D.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Comprende el significado de palabras de uso frecuente en el contexto escolar" },
  { code: "APZ_LENTO.D.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Propone al menos una solución a problemas prácticos sencillos (\"¿Qué haces si…?\")" },
  { code: "APZ_LENTO.D.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Identifica la categoría común de 2–3 objetos concretos cuando se le guía con ejemplos" },
  { code: "APZ_LENTO.D.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Resuelve adivinanzas simples con pistas o comprende chistes de estructura sencilla" },
  { code: "APZ_LENTO.D.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Comprende instrucciones escritas de tareas académicas básicas con apoyo visual o verbal" },
  { code: "APZ_LENTO.D.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Puede resolver problemas prácticos y académicos sencillos con la ayuda del docente" },
  { code: "APZ_LENTO.D.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Conecta conocimientos previos con información nueva cuando el docente hace explícito el puente" },
  { code: "APZ_LENTO.D.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Comprende conceptos abstractos básicos cuando se presentan con ejemplos concretos y material visual" },
  { code: "APZ_LENTO.D.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Puede razonar en situaciones concretas y transferir aprendizajes a contextos similares con guía" },
  { code: "APZ_LENTO.D.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "D", areaLabel: "COMPRENSIÓN Y RAZONAMIENTO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Accede a contenidos curriculares adaptados aplicando estrategias de comprensión enseñadas explícitamente" },

  // ── ÁREA E: ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES ──
  { code: "APZ_LENTO.E.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Aprende reglas de juegos simples (2–3 reglas) con 2–3 demostraciones y recordatorios" },
  { code: "APZ_LENTO.E.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Con suficientes repeticiones y apoyos, retiene lo aprendido en la sesión para la siguiente" },
  { code: "APZ_LENTO.E.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Transfiere habilidades aprendidas con material concreto a material semi-concreto con apoyo del docente" },
  { code: "APZ_LENTO.E.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Consolida nuevos aprendizajes con más repeticiones y práctica distribuida que sus pares (2–4× más exposición)" },
  { code: "APZ_LENTO.E.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Aplica lo aprendido en un contexto a otro similar cuando el docente señala explícitamente la conexión" },
  { code: "APZ_LENTO.E.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Con práctica distribuida y repetición sistemática, consolida habilidades básicas de lectoescritura" },
  { code: "APZ_LENTO.E.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Con andamiaje sistemático, puede generalizar estrategias de resolución a nuevos contextos similares" },
  { code: "APZ_LENTO.E.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Retiene aprendizajes entre sesiones cuando se realizan repasos breves y estructurados" },
  { code: "APZ_LENTO.E.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Aplica estrategias aprendidas a situaciones nuevas similares cuando el docente señala la conexión" },
  { code: "APZ_LENTO.E.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Con apoyo constante y planificado, logra avanzar en los contenidos curriculares adaptados" },
  { code: "APZ_LENTO.E.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Ha consolidado habilidades básicas de lectoescritura y cálculo con el apoyo sostenido del servicio" },
  { code: "APZ_LENTO.E.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "E", areaLabel: "ADQUISICIÓN Y GENERALIZACIÓN DE APRENDIZAJES", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Puede generalizar lo aprendido a contextos cotidianos con apoyo y práctica consistente" },

  // ── ÁREA F: DESARROLLO DEL LENGUAJE Y VOCABULARIO ──
  { code: "APZ_LENTO.F.1.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Nombra objetos cotidianos y personajes de cuentos con vocabulario básico funcional" },
  { code: "APZ_LENTO.F.1.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Produce oraciones simples de 3–5 palabras para comunicar ideas o necesidades" },
  { code: "APZ_LENTO.F.2.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Comprende el significado de palabras de uso frecuente en el contexto escolar" },
  { code: "APZ_LENTO.F.2.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Narra brevemente una experiencia personal con oraciones simples y pausas normales" },
  { code: "APZ_LENTO.F.3.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Comprende historias cortas y responde preguntas literales sobre su contenido" },
  { code: "APZ_LENTO.F.3.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Responde a preguntas abiertas produciendo al menos 2–3 oraciones coherentes" },
  { code: "APZ_LENTO.F.4.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Puede explicar el significado de palabras familiares con sus propias palabras" },
  { code: "APZ_LENTO.F.4.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Se expresa oralmente de forma comprensible aunque su vocabulario sea más limitado que el promedio del grupo" },
  { code: "APZ_LENTO.F.5.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Comprende instrucciones verbales complejas cuando se presentan despacio, con claridad y apoyos" },
  { code: "APZ_LENTO.F.5.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Su expresión oral, aunque limitada en vocabulario, es suficiente para participar en diálogos del aula" },
  { code: "APZ_LENTO.F.6.1", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Comunica ideas con oraciones completas aunque con vocabulario más simple que sus pares" },
  { code: "APZ_LENTO.F.6.2", difficulty: "APZ_LENTO", difficultyLabel: "Aprendizaje lento", areaCode: "F", areaLabel: "DESARROLLO DEL LENGUAJE Y VOCABULARIO", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Puede producir textos escritos breves y coherentes con apoyo de plantillas o guías de escritura" },


  // ============================================================
  // TANV — Trastorno del Aprendizaje No Verbal
  // Fuente: Anexo 5 + estándares internacionales (Rourke, DSM-5)
  // ============================================================

  // ── ÁREA A: HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS ──
  { code: "TANV.A.1.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Copia figuras geométricas básicas (círculo, cuadrado, triángulo) con proporciones reconocibles" },
  { code: "TANV.A.1.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Ensambla rompecabezas de 6–8 piezas o completa figuras incompletas sin confusión marcada de orientación" },
  { code: "TANV.A.1.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 3, description: "Diferencia figuras idénticas en distintas posiciones (rotadas, reflejadas) sin confusión marcada" },
  { code: "TANV.A.2.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Copia diseños simétricos simples a partir de un modelo sin inversiones o distorsiones marcadas" },
  { code: "TANV.A.2.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Organiza elementos visuales en el espacio de la hoja de forma coherente (no agolpados ni desbordados)" },
  { code: "TANV.A.2.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 3, description: "Identifica la figura oculta en imágenes de figura-fondo sin confundirlas marcadamente" },
  { code: "TANV.A.3.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Reproduce patrones geométricos de complejidad media sin perder la estructura general del modelo" },
  { code: "TANV.A.3.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Orienta su trabajo escrito en el espacio de la hoja con márgenes y líneas relativamente respetados" },
  { code: "TANV.A.3.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 3, description: "Puede construir figuras con bloques o piezas siguiendo un modelo visual sencillo" },
  { code: "TANV.A.4.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Lee y reproduce gráficas, mapas o diagramas simples sin confundir referencias espaciales" },
  { code: "TANV.A.4.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Mantiene la organización espacial en operaciones matemáticas escritas (columnas, cifras alineadas)" },
  { code: "TANV.A.4.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 3, description: "Puede interpretar esquemas o diagramas académicos básicos sin dificultad marcada" },
  { code: "TANV.A.5.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Puede interpretar planos sencillos, mapas o representaciones bidimensionales del espacio" },
  { code: "TANV.A.5.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Produce figuras geométricas y representaciones visuales con suficiente precisión para el grado" },
  { code: "TANV.A.5.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 3, description: "Comprende conceptos de simetría, transformaciones y figuras geométricas con apoyos concretos" },
  { code: "TANV.A.6.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Interpreta gráficos estadísticos, diagramas de flujo y representaciones visuales académicas" },
  { code: "TANV.A.6.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Resuelve problemas que requieren razonamiento espacial (geometría) con apoyos visuales" },
  { code: "TANV.A.6.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "A", areaLabel: "HABILIDADES VISOESPACIALES Y VISOCONSTRUCTIVAS", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 3, description: "Organiza información visual compleja (cuadros comparativos, mapas mentales) de forma funcional con apoyo" },

  // ── ÁREA B: MOTRICIDAD FINA Y COORDINACIÓN ──
  { code: "TANV.B.1.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Agarra el lápiz con una postura funcional (no necesariamente perfecta, pero eficiente para la tarea)" },
  { code: "TANV.B.1.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Recorta figuras con tijeras con resultado reconocible sin excesiva irregularidad" },
  { code: "TANV.B.1.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 3, description: "Puede ensartar cuentas grandes o realizar nudos básicos sin frustración excesiva" },
  { code: "TANV.B.2.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "La escritura a mano es legible aunque puede ser más lenta o irregular que la del promedio del grupo" },
  { code: "TANV.B.2.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Puede realizar actividades de pegado, doblado y recortado con resultado funcional" },
  { code: "TANV.B.2.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 3, description: "Manipula objetos pequeños (fichas, monedas, botones) con control suficiente para actividades académicas" },
  { code: "TANV.B.3.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Escribe con la presión adecuada (no excesivamente fuerte ni débil) para producir texto legible" },
  { code: "TANV.B.3.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Puede realizar secuencias de movimientos motores finos (abotonarse, pinchar, trenzar) con tiempo adicional" },
  { code: "TANV.B.3.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 3, description: "En actividades físicas, puede realizar coordinaciones bilaterales básicas (tocar rodilla con codo opuesto)" },
  { code: "TANV.B.4.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "La velocidad de escritura a mano es funcional, aunque puede requerir más tiempo que el promedio" },
  { code: "TANV.B.4.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Puede usar herramientas básicas (compás, regla, transportador) con guía inicial y práctica" },
  { code: "TANV.B.4.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 3, description: "La coordinación óculo-manual es suficiente para actividades académicas con las adaptaciones correspondientes" },
  { code: "TANV.B.5.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Produce texto escrito legible en condiciones normales de trabajo con el tiempo necesario" },
  { code: "TANV.B.5.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Puede participar en actividades de motricidad gruesa sin dificultades marcadas de coordinación" },
  { code: "TANV.B.5.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 3, description: "El nivel de motricidad fina no le impide acceder a actividades académicas con adaptaciones" },
  { code: "TANV.B.6.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "La escritura manual es funcional y legible, aunque puede ser más lenta" },
  { code: "TANV.B.6.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Puede usar teclado u otras herramientas tecnológicas como alternativa funcional a la escritura manual" },
  { code: "TANV.B.6.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "B", areaLabel: "MOTRICIDAD FINA Y COORDINACIÓN", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 3, description: "Las dificultades motoras no son el principal obstáculo para el acceso al currículo con los apoyos adecuados" },

  // ── ÁREA C: RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL ──
  { code: "TANV.C.1.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Asocia número con cantidad de objetos de forma funcional (concepto cardinal básico)" },
  { code: "TANV.C.1.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Comprende conceptos espaciales básicos: arriba/abajo, dentro/fuera, cerca/lejos, al lado" },
  { code: "TANV.C.1.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 3, description: "Identifica y nombra figuras geométricas básicas en contextos concretos" },
  { code: "TANV.C.2.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Resuelve operaciones de suma y resta sencillas con apoyo concreto o semi-concreto" },
  { code: "TANV.C.2.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Comprende la secuencia numérica y puede ubicar números en la recta numérica básica" },
  { code: "TANV.C.2.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 3, description: "Identifica relaciones espaciales en el plano: izquierda/derecha, posición relativa de objetos" },
  { code: "TANV.C.3.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Resuelve problemas matemáticos sencillos con lectura textual aunque con dificultad en la representación espacial" },
  { code: "TANV.C.3.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Puede orientarse en el espacio del aula y seguir indicaciones espaciales de 2–3 pasos" },
  { code: "TANV.C.3.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 3, description: "Comprende el valor posicional de los números con apoyos visuales y material concreto" },
  { code: "TANV.C.4.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Resuelve operaciones aritméticas de complejidad media con apoyos visuales organizados" },
  { code: "TANV.C.4.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Con apoyo, puede leer e interpretar gráficas de barras o tablas simples" },
  { code: "TANV.C.4.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 3, description: "Las dificultades de orientación espacial no le impiden acceder a contenidos matemáticos con adaptaciones" },
  { code: "TANV.C.5.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Puede resolver problemas matemáticos verbales con apoyo de representación visual o concreta" },
  { code: "TANV.C.5.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Comprende conceptos geométricos básicos (perímetro, área) cuando se presentan con modelos concretos" },
  { code: "TANV.C.5.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 3, description: "Con estrategias compensatorias (verbalización del proceso), accede a los contenidos matemáticos del grado" },
  { code: "TANV.C.6.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Con apoyos sistemáticos, puede resolver problemas matemáticos del nivel con eficiencia funcional" },
  { code: "TANV.C.6.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Comprende y aplica operaciones con fracciones y porcentajes con apoyo visual estructurado" },
  { code: "TANV.C.6.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "C", areaLabel: "RAZONAMIENTO MATEMÁTICO NO VERBAL Y ORIENTACIÓN ESPACIAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 3, description: "Las dificultades de razonamiento no verbal no le impiden el acceso al currículo con las adaptaciones planificadas" },

  // ── ÁREA D: COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA ──
  { code: "TANV.D.1.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Puede responder preguntas literales sobre textos breves escuchados o leídos con apoyo" },
  { code: "TANV.D.1.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Comprende el sentido básico de oraciones simples sin malinterpretaciones frecuentes" },
  { code: "TANV.D.2.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Comprende textos de 2–3 oraciones con vocabulario simple a nivel literal" },
  { code: "TANV.D.2.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Puede producir frases escritas simples comunicando una idea básica" },
  { code: "TANV.D.3.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Comprende el significado literal de párrafos cortos al nivel esperado para el grado" },
  { code: "TANV.D.3.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "Realiza inferencias básicas sobre textos simples con guía del docente (\"¿Por qué crees que…?\")" },
  { code: "TANV.D.3.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 3, description: "Produce párrafos simples con inicio, desarrollo y final con apoyo de guía estructural" },
  { code: "TANV.D.4.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Comprende textos expositivos cortos a nivel literal con vocabulario conocido" },
  { code: "TANV.D.4.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Realiza inferencias de nivel 1 (causa-efecto directo) con andamiaje del docente" },
  { code: "TANV.D.4.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 3, description: "Su expresión escrita comunica la idea principal aunque con estructura básica" },
  { code: "TANV.D.5.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Comprende textos narrativos e informativos a nivel literal e inferencial básico con apoyo" },
  { code: "TANV.D.5.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Puede identificar la idea principal y algunos detalles relevantes en un texto de su nivel" },
  { code: "TANV.D.5.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 3, description: "Produce texto escrito estructurado con orientación explícita de la tarea" },
  { code: "TANV.D.6.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Comprende textos académicos con vocabulario técnico cuando se preparan los conceptos clave previamente" },
  { code: "TANV.D.6.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Produce respuestas escritas coherentes a preguntas de comprensión con estructura básica" },
  { code: "TANV.D.6.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "D", areaLabel: "COMPRENSIÓN LECTORA INFERENCIAL Y EXPRESIÓN ESCRITA", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 3, description: "La comprensión lectora inferencial, aunque por debajo del promedio, es funcional con los apoyos planificados" },

  // ── ÁREA E: HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL ──
  { code: "TANV.E.1.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 1, description: "Puede participar en juegos grupales siguiendo reglas básicas con ayuda del adulto" },
  { code: "TANV.E.1.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "1", levelLabel: "1° Grado", levelType: "checkbox", levelSort: 1, itemOrder: 2, description: "Responde a saludos, expresiones faciales básicas (alegría, tristeza) y gestos cotidianos conocidos" },
  { code: "TANV.E.2.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 1, description: "Interactúa con pares en situaciones estructuradas sin conflictos frecuentes" },
  { code: "TANV.E.2.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "2", levelLabel: "2° Grado", levelType: "checkbox", levelSort: 2, itemOrder: 2, description: "Reconoce emociones básicas en imágenes o situaciones descritas (contento, enojado, asustado, triste)" },
  { code: "TANV.E.3.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 1, description: "Puede mantener una conversación breve sobre un tema de su interés con un interlocutor adulto" },
  { code: "TANV.E.3.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 2, description: "No confunde frecuentemente el tono de voz ni la intención comunicativa en situaciones conocidas" },
  { code: "TANV.E.3.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "3", levelLabel: "3° Grado", levelType: "checkbox", levelSort: 3, itemOrder: 3, description: "Puede integrarse en actividades de grupo con mediación ocasional del adulto" },
  { code: "TANV.E.4.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 1, description: "Comprende normas sociales básicas del aula y las sigue con recordatorios ocasionales" },
  { code: "TANV.E.4.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 2, description: "Reconoce cuando una persona está molesta o contenta a partir de señales contextuales explícitas" },
  { code: "TANV.E.4.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "4", levelLabel: "4° Grado", levelType: "checkbox", levelSort: 4, itemOrder: 3, description: "Con apoyo, puede resolver conflictos sencillos usando palabras en lugar de reacciones físicas" },
  { code: "TANV.E.5.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 1, description: "Puede interpretar el significado principal de expresiones faciales y gestos en contextos conocidos" },
  { code: "TANV.E.5.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 2, description: "Con guía, puede adaptar su comportamiento a distintos contextos sociales (aula, recreo, biblioteca)" },
  { code: "TANV.E.5.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "5", levelLabel: "5° Grado", levelType: "checkbox", levelSort: 5, itemOrder: 3, description: "No muestra aislamiento social marcado ni rechazos persistentes por parte de sus pares" },
  { code: "TANV.E.6.1", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 1, description: "Comprende el sentido literal y básico de expresiones del lenguaje social cotidiano" },
  { code: "TANV.E.6.2", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 2, description: "Puede mantener interacciones funcionales con pares y adultos en contextos estructurados" },
  { code: "TANV.E.6.3", difficulty: "TANV", difficultyLabel: "Aprendizaje no verbal (TANV)", areaCode: "E", areaLabel: "HABILIDADES SOCIALES Y COMUNICACIÓN NO VERBAL", level: "6", levelLabel: "6° Grado", levelType: "checkbox", levelSort: 6, itemOrder: 3, description: "Con apoyo, puede identificar y aplicar estrategias básicas para las situaciones sociales del aula" },
]
