/**
 * Datos de catálogos basados en:
 * - Líneas de Acción MEP 2023 (2ª edición)
 * - Cuaderno Complementario N°4 – Problemas de Aprendizaje (2023)
 * - Instrumento de Valoración Integral 2026
 * - Informe de Valoración Integral 2026
 */

// ============================================================
// BARRIER ITEMS
// Categorías: contexto_aula | contexto_institucional | contexto_familiar
//             curriculo | metodologia | evaluacion | organizacion | actitudinal
// ============================================================
export const BARRIER_ITEMS = [
  // --- CONTEXTO DEL AULA ---
  {
    code: "BAR.CLA.01",
    label: "Espacio físico reducido o poco funcional para la movilidad",
    category: "contexto_aula",
    description: "El espacio del aula limita los desplazamientos necesarios para actividades o dificulta la concentración del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 1,
  },
  {
    code: "BAR.CLA.02",
    label: "Iluminación insuficiente o inadecuada",
    category: "contexto_aula",
    description: "La iluminación del aula no es adecuada para las actividades de lectura y escritura.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 2,
  },
  {
    code: "BAR.CLA.03",
    label: "Exceso de estímulos visuales o auditivos",
    category: "contexto_aula",
    description: "El aula presenta demasiados estímulos (carteles, ruidos, actividad) que generan distracción en el estudiante.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 3,
  },
  {
    code: "BAR.CLA.04",
    label: "Ubicación del estudiante que dificulta la atención",
    category: "contexto_aula",
    description: "El estudiante está ubicado lejos de la pizarra, cerca de la puerta o en un lugar con distractores que afectan su atención.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 4,
  },
  {
    code: "BAR.CLA.05",
    label: "Falta de rutinas y transiciones claras entre actividades",
    category: "contexto_aula",
    description: "La dinámica del aula no cuenta con señales claras de inicio, cierre o cambio de actividad que le den predictibilidad al estudiante.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 5,
  },
  {
    code: "BAR.CLA.06",
    label: "Clima de aula poco favorable para el aprendizaje",
    category: "contexto_aula",
    description: "Las relaciones entre pares o con la docente generan tensión, exclusión o inseguridad que inhibe la participación del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 6,
  },
  // --- CONTEXTO INSTITUCIONAL ---
  {
    code: "BAR.INST.01",
    label: "Recursos materiales y tecnológicos insuficientes en el centro",
    category: "contexto_institucional",
    description: "El centro educativo no cuenta con los materiales o tecnología necesarios para dar soporte al proceso del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 10,
  },
  {
    code: "BAR.INST.02",
    label: "Tiempo reducido para la coordinación entre docentes",
    category: "contexto_institucional",
    description: "El horario institucional no permite espacios de coordinación entre la docente guía y la docente de apoyo.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 11,
  },
  {
    code: "BAR.INST.03",
    label: "Ausencia o escasez de apoyos profesionales en el centro",
    category: "contexto_institucional",
    description: "El centro no cuenta con servicios de orientación, psicología u otros profesionales de apoyo que el estudiante podría requerir.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 12,
  },
  {
    code: "BAR.INST.04",
    label: "Desconocimiento de la comunidad educativa sobre la dificultad",
    category: "contexto_institucional",
    description: "El personal docente y demás miembros de la comunidad educativa no conocen la naturaleza de las dificultades específicas del aprendizaje del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 13,
  },
  {
    code: "BAR.INST.05",
    label: "Cultura institucional poco abierta a la diversidad",
    category: "contexto_institucional",
    description: "El centro educativo no promueve activamente prácticas inclusivas o no valora la diversidad en el aprendizaje.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 14,
  },
  // --- CONTEXTO FAMILIAR ---
  {
    code: "BAR.FAM.01",
    label: "Bajo involucramiento familiar en el proceso educativo",
    category: "contexto_familiar",
    description: "La familia tiene poca participación o disponibilidad para dar seguimiento al proceso educativo del estudiante desde el hogar.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 20,
  },
  {
    code: "BAR.FAM.02",
    label: "Falta de rutinas y estructura en el hogar",
    category: "contexto_familiar",
    description: "El entorno familiar no cuenta con hábitos de estudio, horarios establecidos ni espacios adecuados para que el estudiante realice sus tareas.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 21,
  },
  {
    code: "BAR.FAM.03",
    label: "Recursos materiales o tecnológicos limitados en el hogar",
    category: "contexto_familiar",
    description: "La familia no dispone de materiales básicos de trabajo, acceso a Internet o dispositivos tecnológicos que apoyen el aprendizaje.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 22,
  },
  {
    code: "BAR.FAM.04",
    label: "Dificultades en la comunicación familia-escuela",
    category: "contexto_familiar",
    description: "Existen obstáculos para mantener una comunicación fluida y efectiva entre la familia y el centro educativo.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 23,
  },
  {
    code: "BAR.FAM.05",
    label: "Desconocimiento familiar sobre la dificultad del estudiante",
    category: "contexto_familiar",
    description: "La familia no comprende la naturaleza de las dificultades específicas del aprendizaje ni las estrategias de apoyo en el hogar.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 24,
  },
  // --- CURRÍCULO ---
  {
    code: "BAR.CUR.01",
    label: "Ausencia o desactualización de adecuaciones curriculares",
    category: "curriculo",
    description: "El estudiante no cuenta con adecuaciones curriculares vigentes o estas no reflejan sus necesidades actuales.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 30,
  },
  {
    code: "BAR.CUR.02",
    label: "Materiales didácticos no adaptados a las necesidades del estudiante",
    category: "curriculo",
    description: "Los materiales usados en clase no consideran las formas de aprender del estudiante (tipo de letra, formato, nivel de complejidad).",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 31,
  },
  {
    code: "BAR.CUR.03",
    label: "Ritmo de cobertura curricular incompatible con el ritmo del estudiante",
    category: "curriculo",
    description: "El avance de contenidos en el aula es más rápido que el ritmo de aprendizaje y consolidación del estudiante.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 32,
  },
  {
    code: "BAR.CUR.04",
    label: "Objetivos curriculares no ajustados al nivel real del estudiante",
    category: "curriculo",
    description: "Los aprendizajes esperados están muy por encima o muy por debajo de las posibilidades actuales del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 33,
  },
  // --- METODOLOGÍA ---
  {
    code: "BAR.MET.01",
    label: "Estrategias de mediación pedagógica poco variadas o flexibles",
    category: "metodologia",
    description: "La docente guía utiliza pocas estrategias y no diversifica la presentación de la información según las necesidades del estudiantado.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 40,
  },
  {
    code: "BAR.MET.02",
    label: "Escasa presentación multimodal de la información",
    category: "metodologia",
    description: "La información se presenta principalmente de forma oral o escrita, sin apoyos visuales, auditivos o manipulativos.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 41,
  },
  {
    code: "BAR.MET.03",
    label: "Pocas oportunidades de expresión diversa para el estudiante",
    category: "metodologia",
    description: "El estudiante no tiene muchas opciones para demostrar lo que sabe de formas diferentes a la escritura o la prueba formal.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 42,
  },
  {
    code: "BAR.MET.04",
    label: "Actividades poco motivantes o desconectadas de los intereses del estudiante",
    category: "metodologia",
    description: "Las actividades no captan la atención ni la motivación del estudiante porque no se vinculan con sus intereses o no representan un reto adecuado.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 43,
  },
  {
    code: "BAR.MET.05",
    label: "Falta de implementación de DUA u otras metodologías activas",
    category: "metodologia",
    description: "No se aplican principios del Diseño Universal para el Aprendizaje ni metodologías activas y participativas en el aula.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 44,
  },
  // --- EVALUACIÓN ---
  {
    code: "BAR.EVA.01",
    label: "Formas de evaluación rígidas que no consideran la diversidad",
    category: "evaluacion",
    description: "Las pruebas y actividades evaluativas tienen un único formato que no permite que el estudiante demuestre sus aprendizajes de distintas formas.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 50,
  },
  {
    code: "BAR.EVA.02",
    label: "Tiempo insuficiente para completar tareas y pruebas",
    category: "evaluacion",
    description: "El tiempo asignado no es suficiente para que el estudiante complete las pruebas o actividades evaluativas con el ritmo que necesita.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 51,
  },
  {
    code: "BAR.EVA.03",
    label: "Ausencia de adecuaciones evaluativas específicas",
    category: "evaluacion",
    description: "No existen ajustes en los instrumentos de evaluación que correspondan a las necesidades del estudiante (formato, tiempo, modalidad).",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 52,
  },
  {
    code: "BAR.EVA.04",
    label: "Formato de prueba que no favorece la demostración del conocimiento",
    category: "evaluacion",
    description: "El tipo de pregunta, la distribución o el formato de los instrumentos no permiten que el estudiante muestre lo que sabe.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 53,
  },
  // --- ORGANIZACIÓN ---
  {
    code: "BAR.ORG.01",
    label: "Tamaño del grupo que dificulta la atención individualizada",
    category: "organizacion",
    description: "La cantidad de estudiantes en el aula hace difícil que la docente pueda dar atención personalizada al estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 60,
  },
  {
    code: "BAR.ORG.02",
    label: "Horario o distribución del tiempo que no favorece el aprendizaje",
    category: "organizacion",
    description: "La organización del tiempo lectivo no considera las necesidades de concentración y descanso del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 61,
  },
  {
    code: "BAR.ORG.03",
    label: "Falta de coordinación entre los docentes que atienden al estudiante",
    category: "organizacion",
    description: "No existe una coordinación sistemática entre la docente guía, docente de apoyo y otros profesionales que atienden al estudiante.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 62,
  },
  // --- ACTITUDINAL ---
  {
    code: "BAR.ACT.01",
    label: "Bajas expectativas del personal docente hacia el estudiante",
    category: "actitudinal",
    description: "Las personas docentes tienen expectativas reducidas sobre las posibilidades de aprendizaje y progreso del estudiante.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 70,
  },
  {
    code: "BAR.ACT.02",
    label: "Prejuicios o estereotipos sobre la dificultad del aprendizaje",
    category: "actitudinal",
    description: "Existen creencias negativas o estereotipos en la comunidad educativa sobre el estudiantado con dificultades específicas del aprendizaje.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 71,
  },
  {
    code: "BAR.ACT.03",
    label: "Poca valoración de la voz del estudiante en su proceso educativo",
    category: "actitudinal",
    description: "No se toman en cuenta los intereses, opiniones y perspectivas del estudiante en la construcción de su plan de apoyo y estrategias.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 72,
  },
  {
    code: "BAR.ACT.04",
    label: "Estigma o exclusión social de compañeros",
    category: "actitudinal",
    description: "El estudiante enfrenta rechazo, burlas o exclusión por parte de sus compañeros relacionado con sus dificultades de aprendizaje.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 73,
  },
];

// ============================================================
// CONTEXT DIMENSIONS
// Dimensiones observables para guiar la descripción del contexto
// dimension: aula | institucional | familiar
// ============================================================
export const CONTEXT_DIMENSIONS = [
  // --- AULA ---
  {
    code: "DIM.CLA.01",
    label: "Espacio y disposición del mobiliario",
    dimension: "aula",
    description: "Organización física del aula, disposición de mesas, acceso a materiales.",
    guideText: "Describa cómo está organizado el espacio del aula, la ubicación del estudiante y si el espacio favorece o dificulta su participación.",
    sortOrder: 1,
  },
  {
    code: "DIM.CLA.02",
    label: "Iluminación y ventilación",
    dimension: "aula",
    description: "Condiciones ambientales básicas del aula.",
    guideText: "Indique si la iluminación y la ventilación del aula son adecuadas para las actividades de aprendizaje.",
    sortOrder: 2,
  },
  {
    code: "DIM.CLA.03",
    label: "Nivel de estímulos y distractores",
    dimension: "aula",
    description: "Cantidad y tipo de estímulos visuales y auditivos presentes en el aula.",
    guideText: "Describa si el aula tiene muchos carteles, decoración, ruido externo u otros estímulos que puedan distraer al estudiante.",
    sortOrder: 3,
  },
  {
    code: "DIM.CLA.04",
    label: "Rutinas y transiciones entre actividades",
    dimension: "aula",
    description: "Existencia y claridad de rutinas diarias en el aula.",
    guideText: "Indique si existen rutinas claras de inicio, desarrollo y cierre de las actividades, y si las transiciones son predecibles para el estudiante.",
    sortOrder: 4,
  },
  {
    code: "DIM.CLA.05",
    label: "Clima de aula y relaciones interpersonales",
    dimension: "aula",
    description: "Ambiente emocional y relaciones entre el estudiantado y con la docente.",
    guideText: "Describa el ambiente emocional del aula: ¿el estudiante se siente seguro, aceptado, incluido por sus compañeros y la docente?",
    sortOrder: 5,
  },
  {
    code: "DIM.CLA.06",
    label: "Metodología y estrategias de la docente guía",
    dimension: "aula",
    description: "Estrategias y metodologías que usa la docente en la mediación pedagógica.",
    guideText: "Describa las estrategias que usa la docente: ¿varía la presentación de la información? ¿permite diversas formas de expresión? ¿usa materiales visuales?",
    sortOrder: 6,
  },
  {
    code: "DIM.CLA.07",
    label: "Tiempo disponible para las tareas y actividades",
    dimension: "aula",
    description: "Gestión del tiempo en las actividades del aula.",
    guideText: "Señale si el tiempo que se asigna para las actividades es suficiente para el ritmo de trabajo del estudiante.",
    sortOrder: 7,
  },
  // --- INSTITUCIONAL ---
  {
    code: "DIM.INST.01",
    label: "Recursos materiales y tecnológicos del centro",
    dimension: "institucional",
    description: "Disponibilidad de materiales didácticos, tecnología y recursos físicos en el centro.",
    guideText: "Indique qué recursos tiene el centro para apoyar al estudiante: libros adaptados, tecnología, materiales especializados, etc.",
    sortOrder: 10,
  },
  {
    code: "DIM.INST.02",
    label: "Servicios de apoyo disponibles en el centro",
    dimension: "institucional",
    description: "Disponibilidad de servicios de orientación, psicología, terapia u otros apoyos.",
    guideText: "Mencione los servicios de apoyo con que cuenta el centro: orientación, psicología educativa, servicios de problemas de aprendizaje, terapia del lenguaje, otros.",
    sortOrder: 11,
  },
  {
    code: "DIM.INST.03",
    label: "Coordinación entre docentes y servicios de apoyo",
    dimension: "institucional",
    description: "Calidad y frecuencia de la coordinación entre el personal docente y los servicios de apoyo.",
    guideText: "Describa cómo es la coordinación entre la docente guía y la docente de apoyo: ¿hay espacios regulares de trabajo colaborativo?",
    sortOrder: 12,
  },
  {
    code: "DIM.INST.04",
    label: "Cultura institucional hacia la diversidad e inclusión",
    dimension: "institucional",
    description: "Nivel de apertura y compromiso del centro con prácticas inclusivas.",
    guideText: "Indique si el centro promueve activamente la inclusión y la atención a la diversidad: ¿existe un Comité de Apoyo Educativo activo?",
    sortOrder: 13,
  },
  {
    code: "DIM.INST.05",
    label: "Accesibilidad física del centro educativo",
    dimension: "institucional",
    description: "Condiciones físicas del centro que facilitan o dificultan la participación del estudiante.",
    guideText: "Señale si el centro cuenta con las condiciones físicas necesarias para la participación plena del estudiante.",
    sortOrder: 14,
  },
  // --- FAMILIAR ---
  {
    code: "DIM.FAM.01",
    label: "Involucramiento y compromiso familiar",
    dimension: "familiar",
    description: "Nivel de participación activa de la familia en el proceso educativo.",
    guideText: "Describa el nivel de participación de la familia: ¿asisten a reuniones? ¿dan seguimiento a las estrategias de apoyo en el hogar?",
    sortOrder: 20,
  },
  {
    code: "DIM.FAM.02",
    label: "Dinámica y estructura familiar",
    dimension: "familiar",
    description: "Composición del grupo familiar y dinámica de las relaciones.",
    guideText: "Describa brevemente la composición familiar y si existen elementos de la dinámica familiar que favorecen o dificultan el proceso educativo.",
    sortOrder: 21,
  },
  {
    code: "DIM.FAM.03",
    label: "Rutinas y espacio de estudio en el hogar",
    dimension: "familiar",
    description: "Existencia de hábitos de estudio, horarios y espacio físico adecuado en el hogar.",
    guideText: "Señale si el estudiante tiene un lugar tranquilo para hacer tareas, con rutinas establecidas y tiempo suficiente para el estudio.",
    sortOrder: 22,
  },
  {
    code: "DIM.FAM.04",
    label: "Recursos materiales y tecnológicos en el hogar",
    dimension: "familiar",
    description: "Disponibilidad de materiales y tecnología en el entorno familiar.",
    guideText: "Indique si el hogar cuenta con materiales básicos de trabajo escolar, acceso a Internet y dispositivos tecnológicos.",
    sortOrder: 23,
  },
  {
    code: "DIM.FAM.05",
    label: "Comunicación familia-escuela",
    dimension: "familiar",
    description: "Calidad y frecuencia de la comunicación entre la familia y el centro educativo.",
    guideText: "Describa cómo es la comunicación entre la familia y la docente de apoyo o la docente guía: ¿es fluida, frecuente, efectiva?",
    sortOrder: 24,
  },
];

// ============================================================
// SUPPORT ITEMS
// Apoyos educativos requeridos
// Categorías: personal | curricular | metodologico | evaluativo | organizativo | material_tecnologico
// ============================================================
export const SUPPORT_ITEMS = [
  // --- PERSONAL ---
  {
    code: "SUP.PER.01",
    label: "Continuidad del apoyo en el servicio de Problemas de Aprendizaje",
    category: "personal",
    description: "La persona estudiante continúa requiriendo el servicio de apoyo educativo en el área de problemas de aprendizaje.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 1,
  },
  {
    code: "SUP.PER.02",
    label: "Apoyo del servicio de Orientación del centro educativo",
    category: "personal",
    description: "Coordinación y apoyo desde el servicio de orientación para acompañar el área socio-emocional del estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 2,
  },
  {
    code: "SUP.PER.03",
    label: "Apoyo del servicio de Psicología Educativa",
    category: "personal",
    description: "Intervención del servicio de psicología educativa para apoyar aspectos cognitivos, emocionales o conductuales.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 3,
  },
  {
    code: "SUP.PER.04",
    label: "Trabajo colaborativo con docente guía (docencia compartida)",
    category: "personal",
    description: "La docente de apoyo y la docente guía planifican y ejecutan conjuntamente estrategias en el contexto del aula.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 4,
  },
  {
    code: "SUP.PER.05",
    label: "Coordinación con la familia para generalización de estrategias en el hogar",
    category: "personal",
    description: "Se establecen reuniones y comunicación periódica con la familia para que las estrategias del plan de apoyo se generalicen en el contexto familiar.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 5,
  },
  {
    code: "SUP.PER.06",
    label: "Apoyo de Terapia del Lenguaje",
    category: "personal",
    description: "Coordinación o referencia al servicio de terapia del lenguaje para aspectos de comunicación o expresión verbal.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 6,
  },
  // --- CURRICULAR ---
  {
    code: "SUP.CUR.01",
    label: "Adecuación curricular no significativa vigente",
    category: "curricular",
    description: "El estudiante requiere adecuaciones en el proceso de enseñanza y aprendizaje que no modifican los aprendizajes esperados del currículo.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 10,
  },
  {
    code: "SUP.CUR.02",
    label: "Adecuación curricular significativa vigente",
    category: "curricular",
    description: "El estudiante requiere modificaciones en los aprendizajes esperados del currículo, aprobadas por el Comité de Apoyo Educativo.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 11,
  },
  {
    code: "SUP.CUR.03",
    label: "Ajuste de objetivos y actividades al nivel real del estudiante",
    category: "curricular",
    description: "Las actividades y objetivos de aprendizaje se gradúan según el nivel de desempeño actual del estudiante, desde sus fortalezas.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 12,
  },
  {
    code: "SUP.CUR.04",
    label: "Actividades con contenido vinculado a los intereses del estudiante",
    category: "curricular",
    description: "Se utilizan los intereses y motivaciones del estudiante como punto de partida para las actividades de aprendizaje.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 13,
  },
  // --- METODOLÓGICO ---
  {
    code: "SUP.MET.01",
    label: "Presentación multimodal de la información (visual, auditiva, manipulativa)",
    category: "metodologico",
    description: "La información se presenta de múltiples formas: visual, oral, kinestésica, para acceder al aprendizaje desde diferentes canales sensoriales.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 20,
  },
  {
    code: "SUP.MET.02",
    label: "Uso de apoyos visuales (esquemas, mapas conceptuales, carteles, pictogramas)",
    category: "metodologico",
    description: "Se utilizan organizadores gráficos, esquemas, carteles o pictogramas como apoyo a la comprensión y organización de la información.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 21,
  },
  {
    code: "SUP.MET.03",
    label: "Instrucciones claras, secuenciadas y paso a paso",
    category: "metodologico",
    description: "Las instrucciones de las actividades se dan de forma clara, en pasos pequeños y verificables, evitando instrucciones múltiples y complejas.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 22,
  },
  {
    code: "SUP.MET.04",
    label: "Estrategias mnemotécnicas para la memorización",
    category: "metodologico",
    description: "Se emplean acrónimos, rimas, canciones u otras estrategias mnemotécnicas para facilitar la memorización de reglas, vocabulario o procedimientos.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 23,
  },
  {
    code: "SUP.MET.05",
    label: "Uso de código de color y subrayado diferenciado",
    category: "metodologico",
    description: "Se utilizan colores para diferenciar conceptos, letras, cifras o pasos, facilitando la discriminación visual y la organización de la información.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 24,
  },
  {
    code: "SUP.MET.06",
    label: "Uso de recursos tecnológicos digitales (aplicaciones, software, dispositivos)",
    category: "metodologico",
    description: "Se incorporan recursos tecnológicos como apoyo: procesadores de texto, aplicaciones educativas, tabletas o computadoras.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 25,
  },
  {
    code: "SUP.MET.07",
    label: "Actividades lúdicas, juego y gamificación",
    category: "metodologico",
    description: "Se diseñan actividades con componente lúdico, juegos o elementos de gamificación que activen la emoción, la motivación y la atención.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 26,
  },
  {
    code: "SUP.MET.08",
    label: "Uso de material concreto y manipulativo",
    category: "metodologico",
    description: "Se utilizan objetos concretos, material manipulativo o representaciones físicas para construir conceptos matemáticos, escritura u otros.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 27,
  },
  {
    code: "SUP.MET.09",
    label: "Fichas de vocabulario y materiales de referencia personalizados",
    category: "metodologico",
    description: "Se elaboran glosarios, fichas de vocabulario clave o materiales de referencia personalizados para el estudiante.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 28,
  },
  {
    code: "SUP.MET.10",
    label: "Lectura en voz alta y apoyo auditivo de textos",
    category: "metodologico",
    description: "Se lee en voz alta para el estudiante o se permite el uso de herramientas de texto a voz para acceder a los contenidos escritos.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 29,
  },
  // --- EVALUATIVO ---
  {
    code: "SUP.EVA.01",
    label: "Tiempo adicional en pruebas y actividades de evaluación",
    category: "evaluativo",
    description: "Se otorga tiempo extra al estudiante para completar instrumentos de evaluación, acorde a su ritmo de procesamiento.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 30,
  },
  {
    code: "SUP.EVA.02",
    label: "Pruebas con formato adaptado (letra ampliada, espaciado, imágenes)",
    category: "evaluativo",
    description: "Los instrumentos de evaluación se presentan en formato adaptado: letra más grande, mayor espacio entre líneas, apoyo de imágenes.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 31,
  },
  {
    code: "SUP.EVA.03",
    label: "Evaluación oral en sustitución o complemento de la escrita",
    category: "evaluativo",
    description: "Se permite al estudiante demostrar sus aprendizajes de forma oral cuando la expresión escrita representa una barrera significativa.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 32,
  },
  {
    code: "SUP.EVA.04",
    label: "Evaluación continua con rúbricas u otros instrumentos flexibles",
    category: "evaluativo",
    description: "Se utilizan rúbricas, listas de cotejo u otros instrumentos de evaluación formativa que valoren el proceso además del producto.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 33,
  },
  {
    code: "SUP.EVA.05",
    label: "Reducción de ítems en pruebas (mismo contenido, menos cantidad)",
    category: "evaluativo",
    description: "Se reduce la cantidad de ítems manteniendo la cobertura de contenidos, para que la longitud del instrumento no sea una barrera.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 34,
  },
  // --- ORGANIZATIVO ---
  {
    code: "SUP.ORG.01",
    label: "Ubicación estratégica del estudiante en el aula",
    category: "organizativo",
    description: "El estudiante se ubica cerca de la pizarra, lejos de distractores y en un lugar que facilite su participación y atención.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 40,
  },
  {
    code: "SUP.ORG.02",
    label: "Uso de agenda visual o pictográfica para la organización del tiempo",
    category: "organizativo",
    description: "Se utiliza una agenda visual que indica al estudiante las actividades del día, las transiciones y los tiempos esperados.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 41,
  },
  {
    code: "SUP.ORG.03",
    label: "Organización del espacio de trabajo personal (señaladores, mesa ordenada)",
    category: "organizativo",
    description: "Se establecen estrategias para que el estudiante mantenga su espacio de trabajo organizado: señaladores, etiquetas, canastas de materiales.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 42,
  },
  {
    code: "SUP.ORG.04",
    label: "Pausas activas durante las actividades",
    category: "organizativo",
    description: "Se programan pausas breves y activas entre actividades para que el estudiante recupere la atención y la energía.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 43,
  },
  {
    code: "SUP.ORG.05",
    label: "Agrupamiento flexible según el tipo de actividad",
    category: "organizativo",
    description: "Se varía el agrupamiento del estudiantado (individual, parejas, grupos pequeños) según el propósito de la actividad, favoreciendo la participación.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 44,
  },
  // --- MATERIAL Y TECNOLÓGICO ---
  {
    code: "SUP.MAT.01",
    label: "Cuaderno cuadriculado para escritura",
    category: "material_tecnologico",
    description: "Se utiliza cuaderno cuadriculado para apoyar la escritura y el trazado de letras y números.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 50,
  },
  {
    code: "SUP.MAT.02",
    label: "Adaptador o engrosador para el lápiz o lapicero",
    category: "material_tecnologico",
    description: "Se usa un engrosador o adaptador de escritura para facilitar la prensión del instrumento de escritura.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 51,
  },
  {
    code: "SUP.MAT.03",
    label: "Material impreso con letra clara, tamaño adecuado y espaciado amplio",
    category: "material_tecnologico",
    description: "Los materiales impresos usados por el estudiante tienen letra clara, tamaño mínimo 12-14pt y espaciado entre líneas amplio.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 52,
  },
  {
    code: "SUP.MAT.04",
    label: "Dispositivo tecnológico como producto de apoyo (tableta, computadora)",
    category: "material_tecnologico",
    description: "El estudiante usa una tableta o computadora como apoyo principal para el acceso al currículo y la producción de trabajos escritos.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 53,
  },
  {
    code: "SUP.MAT.05",
    label: "Calculadora como apoyo en actividades matemáticas",
    category: "material_tecnologico",
    description: "Se permite el uso de calculadora para actividades matemáticas cuando el cálculo mecánico es una barrera y el objetivo es el razonamiento.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 54,
  },
  {
    code: "SUP.MAT.06",
    label: "Resaltadores y marcadores de colores",
    category: "material_tecnologico",
    description: "El estudiante usa resaltadores y marcadores de diferentes colores para organizar información, resaltar palabras clave y diferenciar conceptos.",
    serviceTags: ["PA"],
    isCore: true,
    sortOrder: 55,
  },
  {
    code: "SUP.MAT.07",
    label: "Auriculares para minimizar distractores auditivos",
    category: "material_tecnologico",
    description: "El estudiante usa auriculares (con o sin música instrumental) para reducir la interferencia de ruidos del entorno y mejorar la concentración.",
    serviceTags: ["PA"],
    isCore: false,
    sortOrder: 56,
  },
];

// ============================================================
// FOLLOWUP SCHEDULES
// Opciones de seguimiento y revisión del plan de apoyo
// type: periodicidad | modalidad | responsable
// ============================================================
export const FOLLOWUP_SCHEDULES = [
  // --- PERIODICIDAD ---
  {
    code: "FOL.PER.01",
    label: "Semanal — seguimiento informal entre docente guía y docente de apoyo",
    type: "periodicidad",
    description: "Comunicación breve y frecuente entre la docente guía y la de apoyo para ajustar estrategias según el avance diario.",
    sortOrder: 1,
  },
  {
    code: "FOL.PER.02",
    label: "Mensual — revisión de avances del plan con el equipo colaborativo",
    type: "periodicidad",
    description: "Reunión mensual del equipo colaborativo (docente de apoyo, docente guía, familia) para revisar avances y ajustar estrategias.",
    sortOrder: 2,
  },
  {
    code: "FOL.PER.03",
    label: "Al finalizar cada periodo lectivo — revisión integral del plan",
    type: "periodicidad",
    description: "Revisión completa del plan de apoyo al concluir cada periodo, considerando los informes del periodo y la evaluación del estudiantado.",
    sortOrder: 3,
  },
  {
    code: "FOL.PER.04",
    label: "Al inicio del siguiente período lectivo — actualización del plan",
    type: "periodicidad",
    description: "Al inicio de cada periodo se revisa el plan de apoyo para actualizarlo según los cambios en el desempeño, las metas y el contexto.",
    sortOrder: 4,
  },
  {
    code: "FOL.PER.05",
    label: "Al detectar cambios significativos en el desempeño del estudiante",
    type: "periodicidad",
    description: "Se convoca una revisión del plan cuando se detectan avances significativos, retrocesos o cambios en el contexto del estudiante.",
    sortOrder: 5,
  },
  {
    code: "FOL.PER.06",
    label: "Al finalizar el año lectivo — revisión para continuidad o egreso",
    type: "periodicidad",
    description: "Revisión al cierre del año para determinar si el estudiante continúa en el servicio, si requiere ajustes o si puede egresar.",
    sortOrder: 6,
  },
  // --- MODALIDAD ---
  {
    code: "FOL.MOD.01",
    label: "Reunión presencial con la familia",
    type: "modalidad",
    description: "El seguimiento se realiza mediante reuniones presenciales con la familia para compartir avances y acordar estrategias en el hogar.",
    sortOrder: 10,
  },
  {
    code: "FOL.MOD.02",
    label: "Comunicación virtual (llamada, videollamada, mensaje escrito)",
    type: "modalidad",
    description: "El seguimiento se apoya en medios virtuales para mantener comunicación continua con la familia y el equipo docente.",
    sortOrder: 11,
  },
  {
    code: "FOL.MOD.03",
    label: "Observación en contexto de aula",
    type: "modalidad",
    description: "La docente de apoyo realiza observaciones periódicas en el aula para monitorear la implementación de estrategias y el desempeño del estudiante.",
    sortOrder: 12,
  },
  {
    code: "FOL.MOD.04",
    label: "Revisión de producciones del estudiante (trabajos, pruebas, portafolio)",
    type: "modalidad",
    description: "Se analiza periódicamente el trabajo producido por el estudiante para verificar avances y ajustar objetivos.",
    sortOrder: 13,
  },
  // --- RESPONSABLE ---
  {
    code: "FOL.RES.01",
    label: "Docente del servicio de Problemas de Aprendizaje (lidera)",
    type: "responsable",
    description: "La docente de apoyo educativo en problemas de aprendizaje lidera el seguimiento del plan de apoyo.",
    sortOrder: 20,
  },
  {
    code: "FOL.RES.02",
    label: "Docente guía (co-lidera en el contexto de aula)",
    type: "responsable",
    description: "La docente a cargo del grupo lidera el seguimiento de las estrategias dentro del aula.",
    sortOrder: 21,
  },
  {
    code: "FOL.RES.03",
    label: "Familia (responsable de estrategias en el hogar)",
    type: "responsable",
    description: "La familia asume la responsabilidad de implementar y dar seguimiento a las estrategias acordadas para el contexto del hogar.",
    sortOrder: 22,
  },
  {
    code: "FOL.RES.04",
    label: "Equipo colaborativo completo (docente apoyo + docente guía + familia)",
    type: "responsable",
    description: "El seguimiento es responsabilidad compartida del equipo colaborativo completo, siguiendo los principios de trabajo colaborativo de las Líneas de Acción.",
    sortOrder: 23,
  },
];
