export function ValoracionIntegral() {
    const listForm = [
        {texto:'Uso del espacio', name:'espacio', value:'', area:'contexto'},
        {texto:'Tiempo', name:'tiempo', value:'', area:'contexto'},
        {texto:'Organización del Mobiliario', name:'organización', value:'', area:'contexto'},
        {texto:'Iluminación del Aula', name:'iluminacion', value:'', area:'contexto'},
        {texto:'Ventilación', name:'ventilacion', value:'', area:'contexto'},
        {texto:'Tamaño', name:'tamaño', value:'', area:'contexto'},
        {texto:'Disposición de los elementos - Estímulos', name:'disposicion', value:'', area:'contexto'},
        {texto:'Transición de las actividades', name:'transicion', value:'', area:'contexto'},
        {texto:'Interacción con la persona doscente', name:'docente', value:'', area:'contexto'},
        {texto:'Interacción con sus iguales', name:'iguales', value:'', area:'contexto'},
        {texto: 'Control de la presión', name:'presión',value:'',area: 'grafia'},
        {texto: 'Posición del papel', name:'papel',value:'',area: 'grafia'},
        {texto: 'Postura en el pupitre', name:'pupitre',value:'',area: 'grafia'},
        {texto: 'Fluidez al escribir', name:'fluidez',value:'',area: 'grafia'},
        {texto: 'Linealidad', name:'linealidad',value:'',area: 'grafia'},
        {texto: 'Separación de letras', name:'separación',value:'',area: 'grafia'},
        {texto: 'Regularidad del tamaño', name:'regularidad',value:'',area: 'grafia'},
        {texto: 'Dificultad para saber los movimientos necesarios para reproducir las letras', name:'movimiento',value:'',area: 'grafia'},
        {texto: 'Dificultades en la percepción ideo-motriz', name:'ideo-motriz',value:'',area: 'grafia'},
        {texto: 'Ausencia de dominancia lateral', name:'dominancia',value:'',area: 'grafia'},
        {texto: 'Dificultades en el tono muscular', name:'tono',value:'',area: 'motricidad'},
        {texto: 'Torpeza manifiesta en la realización de movimientos', name:'torpeza',value:'',area: 'motricidad'},
        {texto: 'Dificultad en seguir el ritmo con una misma actividad o con cambios', name:'ritmo',value:'',area: 'motricidad'},
        {texto: 'Confusión al seguir órdenes motoras simples', name:'ordenes',value:'',area: 'motricidad'},
        {texto: 'Distingue colores e intensidades', name:'colores',value:'',area: 'visual'},
        {texto: 'Diferencia formas simples ', name:'formas',value:'',area: 'visual'},
        {texto: 'Diferencia figuras idénticas en diferentes posiciones ', name:'figuras',value:'',area: 'visual'},
        {texto: 'Expresión oral pobre y dificultades en la articulación de sonidos.', name:'oral',value:'',area: 'auditiva'},
        {texto: 'Falta de atención en el aula, aparenta no escuchar u olvida consignas que se le dan.', name:'atencion',value:'',area: 'auditiva'},
        {texto: 'Sensibilidad al ruido, molestia ante ruidos fuertes.', name:'sensibilidad',value:'',area: 'auditiva'},
        {texto: 'Dificultad para adquirir conceptos derecha –izquierda.', name:'derecha-izquierda',value:'',area: 'espacio'},
        {texto: 'Evitación de juegos de construcción, rompecabezas, etc.', name:'construccion',value:'',area: 'espacio'},
        {texto: 'Dificultad para seguir órdenes sencillas con consignas espaciales.', name:'seguir',value:'',area: 'espacio'},
        {texto: 'Dificultad para organizar los pasos a partir de los cuales se realizan las actividades del aula.', name:'pasos',value:'',area: 'tiempo'},
        {texto: 'Facilidad para perder cosas.', name:'perder',value:'',area: 'tiempo'},
        {texto: 'Dificultad para anticipar consecuencias.', name:'anticipar',value:'',area: 'tiempo'},
        {texto: 'Muestra actitudes de rebeldía para cumplir instrucciones que le dan.', name:'rebeldia',value:'',area: 'madurez'},
        {texto: 'Expresa descontrol emocional cuando algo no sale como debería. ', name:'descontrol',value:'',area: 'madurez'},
        {texto: 'Se mantiene aislado o aislada en actividades de grupo ', name:'aislado',value:'',area: 'madurez'},
        {texto: 'Tiende a jugar en lugar de realizar las actividades de clase', name:'jugar',value:'',area: 'madurez'},
        {texto: ' Invierte letras, sílabas y/o palabras. ', name:'invierte',value:'',area: 'lectoescritura'},
        {texto: 'Confunde el orden de las letras dentro de las palabras (barzo por brazo). ', name:'confunde-orden',value:'',area: 'lectoescritura'},
        {texto: 'Confunde especialmente las letras que tienen una similitud (d/b, u/n...). ', name:'confunde',value:'',area: 'lectoescritura'},
        {texto: 'Omite letras en una palabra (árbo por árbol). ', name:'omite',value:'',area: 'lectoescritura'},
        {texto: ' Sustituye una palabra por otra que empieza por la misma letra (lagarto por letardo). ', name:'sustituye',value:'',area: 'lectoescritura'},
        {texto: 'Tiene dificultades para conectar letras y sonidos. ', name:'conectar',value:'',area: 'lectoescritura'},
        {texto: 'Le cuesta pronunciar palabras, invierte o sustituye sílabas. ', name:'pronunciar',value:'',area: 'lectoescritura'},
        {texto: 'Al leer rectifica, vacila, silabea y/o pierde la línea. ', name:'vacila',value:'',area: 'lectoescritura'},
        {texto: 'Con frecuencia no suele dominar todas las correspondencias entre letras y sonidos. ', name:'correspondencia',value:'',area: 'lectoescritura'},
        {texto: 'Confunde derecha e izquierda. ', name:'lateralidad',value:'',area: 'lectoescritura'},
        {texto: 'Escribe en espejo.', name:'espejo',value:'',area: 'lectoescritura'},
        {texto: 'Su coordinación motriz es pobre. ', name:'pobre',value:'',area: 'lectoescritura'},
        {texto: 'Se dan dificultades para el aprendizaje de secuencias (días de la semana, meses del año, estaciones...). ', name:'secuencia',value:'',area: 'lectoescritura'},
        {texto: 'Le cuesta planificar su tiempo. ', name:'planificar',value:'',area: 'lectoescritura'},
        {texto: 'Trabaja con lentitud. ', name:'lentitud',value:'',area: 'lectoescritura'},
        {texto: 'Evita leer.', name:'evita',value:'',area: 'lectoescritura'},
        {texto: 'Omisiones, adicciones e inversiones de fonemas, sílabas enteras y/o palabras.', name:'fonemas',value:'',area: 'ortograficas'},
        {texto: 'Dificultades para realizar la síntesis y asociación entre fonema y grafema, cambiando unas letras por otras.', name:'sintesis',value:'',area: 'ortograficas'},
        {texto: 'No poner «m» antes de «b» y «p».', name:'m',value:'',area: 'ortograficas'},
        {texto: 'Infringir reglas de puntuación.', name:'puntuacion',value:'',area: 'ortograficas'},
        {texto: 'Respeta  las mayúsculas después de punto o al principio del escrito', name:'mayuscula',value:'',area: 'ortograficas'},
        {texto: 'Escribe con «v» los verbos terminados en «aba».', name:'v',value:'',area: 'ortograficas'},
        {texto: 'Posee el concepto de “número”', name:'numero',value:'',area: 'matematicas'},
        {texto: 'Lee y escribe números.', name:'lee-numero',value:'',area: 'matematicas'},
        {texto: 'Realiza operaciones aritméticas básicas como:', name:'operaciones',value:'',area: 'matematicas'},
        {texto: 'Adición', name:'adicion',value:'',area: 'matematicas'},
        {texto: 'Sustracción', name:'sustraccion',value:'',area: 'matematicas'},
        {texto: 'Multiplicación', name:'multiplicacion',value:'',area: 'matematicas'},
        {texto: ' División', name:'division',value:'',area: 'matematicas'},
        {texto: 'Resuelve problemas matemáticos a nivel de su curso', name:'problemas',value:'',area: 'matematicas'},
        {texto: 'Realiza cálculos escritos en operaciones matemáticas.', name:'calculos-escritos',value:'',area: 'matematicas'},
        {texto: 'Realiza cálculos mentales en operaciones matemáticas.', name:'calculos-mentales',value:'',area: 'matematicas'},
        {texto: 'Realiza las operaciones correspondientes a partir de los signos matemáticos.', name:'signos',value:'',area: 'matematicas'}
    ];
 
    return listForm;
}
